# Generated by Django 3.0.5 on 2020-05-10 00:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_category', models.CharField(max_length=200)),
                ('category_summary', models.CharField(max_length=200)),
                ('category_slug', models.CharField(default=1, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ProjectSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_series', models.CharField(max_length=200)),
                ('series_summary', models.CharField(max_length=200)),
                ('series_slug', models.CharField(default=1, max_length=200)),
                ('project_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dashboard.ProjectCategory', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 5, 10, 1, 51, 49, 580768), verbose_name='Project published on ')),
                ('credentials', models.TextField()),
                ('description', models.TextField()),
                ('expires', models.DateTimeField(default=datetime.datetime(2020, 5, 10, 1, 51, 49, 580768), verbose_name='Project expiries on')),
                ('project_slug', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('project_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dashboard.ProjectCategory', verbose_name='Series')),
                ('project_series', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dashboard.ProjectSeries', verbose_name='Series')),
            ],
            options={
                'verbose_name_plural': 'Project',
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal', models.TextField()),
                ('credential', models.FileField(default=1, upload_to='')),
                ('bid_date', models.DateTimeField(default=datetime.datetime(2020, 5, 10, 1, 51, 49, 582816), verbose_name='Date of Bid')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bids', to='dashboard.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bids',
            },
        ),
    ]
