# Generated by Django 3.0.5 on 2020-05-15 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200510_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 18, 32, 55, 542547), verbose_name='Date of Bid'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 18, 32, 55, 541543), verbose_name='Project published on '),
        ),
        migrations.AlterField(
            model_name='project',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 18, 32, 55, 541543), verbose_name='Project expiries on'),
        ),
    ]
