# Generated by Django 3.0.5 on 2020-05-15 23:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200515_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 16, 0, 31, 2, 22851), verbose_name='Date of Bid'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 16, 0, 31, 2, 17853), verbose_name='Project published on '),
        ),
        migrations.AlterField(
            model_name='project',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 16, 0, 31, 2, 17853), verbose_name='Project expiries on'),
        ),
    ]
