# Generated by Django 3.0.5 on 2020-05-10 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200510_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 1, 47, 20, 114486), verbose_name='date published'),
        ),
    ]
