# Generated by Django 3.0.5 on 2020-05-10 00:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200510_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 1, 50, 19, 286104), verbose_name='date published'),
        ),
    ]
