# Generated by Django 3.0.5 on 2020-05-15 23:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200516_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 16, 0, 31, 28, 231667), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.CharField(max_length=200),
        ),
    ]
